const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
test('CRUD, transfer neutrality, reports, session, reset and no server writes',async({page,context})=>{
  const errors=[],writes=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
  await page.goto('/');await expect(page.getByRole('heading',{name:'家計のダッシュボード'})).toBeVisible();
  const initial=await page.locator('.demo-kpis').textContent();
  await page.getByRole('button',{name:'取引を追加',exact:true}).click();
  await page.getByLabel('金額（円）',{exact:true}).fill('1234');await page.getByLabel('摘要',{exact:true}).fill('E2E lunch <script>');
  await page.getByLabel('カテゴリ（収入 / 支出）').selectOption({label:'支出 / 食費'});
  await page.getByRole('button',{name:'保存して集計に反映'}).click();
  await expect(page.locator('.demo-kpis')).not.toHaveText(initial);
  await page.locator('#demo-filter input').fill('E2E lunch');await page.getByRole('button',{name:'絞り込む'}).click();
  const row=page.locator('tr').filter({hasText:'E2E lunch'});await expect(row).toHaveCount(1);
  await row.getByRole('button',{name:'編集'}).click();await page.getByLabel('金額（円）',{exact:true}).fill('2345');await page.getByRole('button',{name:'保存して集計に反映'}).click();
  await expect(row).toContainText('2,345円');
  await row.getByRole('button',{name:'削除',exact:true}).click();await page.getByRole('button',{name:'削除する',exact:true}).click();
  await expect(page.locator('.demo-kpis')).toHaveText(initial);
  await page.getByRole('button',{name:'取引を追加',exact:true}).click();await page.getByLabel('金額（円）',{exact:true}).fill('2345');await page.getByLabel('摘要',{exact:true}).fill('E2E lunch');await page.getByRole('button',{name:'保存して集計に反映'}).click();
  await page.reload();await expect(page.locator('.demo-kpis')).not.toHaveText(initial);
  await page.locator('.demo-subnav').getByRole('link',{name:'年間の収支'}).click();await expect(page.getByRole('heading',{name:'年間の収支',exact:true})).toBeVisible();
  await expect(page.locator('#demo-chart')).toBeVisible();
  await page.locator('.demo-subnav').getByRole('link',{name:'月別予算の設定'}).click();
  await page.getByRole('row').filter({hasText:'食品・日用品'}).getByRole('button',{name:'変更'}).click();
  await page.getByLabel('予算（円・0は未設定）').fill('0');await page.getByRole('button',{name:'保存して集計に反映'}).click();
  await expect(page.getByRole('row').filter({hasText:'食品・日用品'})).toContainText('未設定');
  await page.locator('.demo-subnav').getByRole('link',{name:'家計のダッシュボード'}).click();
  const beforeTransfer=await page.locator('.demo-kpis').textContent();
  await page.getByRole('button',{name:'口座間振替',exact:true}).click();await page.getByRole('button',{name:'振替を追加',exact:true}).click();
  await page.getByLabel('金額（円）',{exact:true}).fill('1000');await page.getByLabel('摘要',{exact:true}).fill('E2E transfer');await page.getByRole('button',{name:'保存して集計に反映'}).click();
  await expect(page.locator('.demo-kpis')).toHaveText(beforeTransfer);
  await page.goto('/medical-expenses/');await expect(page.locator('.demo-snapshot-note')).toContainText('反映しません');
  await page.goto('/');await page.getByRole('button',{name:'データをリセット'}).click();await page.getByRole('button',{name:'初期データに戻す'}).click();
  await expect(page.locator('.demo-kpis')).toHaveText(initial);
  const fresh=await context.newPage();await fresh.goto('/');await expect(fresh.locator('.demo-kpis')).toHaveText(initial);await fresh.close();
  expect(errors).toEqual([]);expect(writes).toEqual([]);
});
test('mobile, dark theme, keyboard dialog and portfolio screenshots',async({page})=>{
  await page.goto('/2026-08/');await expect(page.getByRole('heading',{name:'家計のダッシュボード'})).toBeVisible();
  await page.goto('/');await expect(page.getByRole('heading',{name:'家計のダッシュボード'})).toBeVisible();
  await page.getByRole('button',{name:'使い方',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'使い方',exact:true})).toBeFocused();
  fs.mkdirSync('artifacts',{recursive:true});
  await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'artifacts/budgetbook-demo-desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='dark');
  await expect(page.locator('body')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.getByRole('button',{name:'取引を追加',exact:true}).click();await expect(page.getByLabel('摘要',{exact:true})).toBeVisible();await page.keyboard.press('Escape');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'artifacts/budgetbook-demo-mobile-dark.png'});
});
